// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Web_Manage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiDat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TongTien")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
